#!/usr/bin/env python3
"""Write a machine-readable environment report and Markdown summary."""

from __future__ import annotations

import importlib
import json
import platform
import sys
from pathlib import Path
from typing import Any


PACKAGES = {
    "torch": "torch",
    "torchvision": "torchvision",
    "ultralytics": "ultralytics",
    "timm": "timm",
    "numpy": "numpy",
    "pandas": "pandas",
    "sklearn": "sklearn",
    "cv2": "cv2",
    "matplotlib": "matplotlib",
    "seaborn": "seaborn",
    "yaml": "yaml",
    "kagglehub": "kagglehub",
}


def package_version(import_name: str) -> str:
    try:
        module = importlib.import_module(import_name)
        return str(getattr(module, "__version__", "unknown"))
    except Exception as exc:
        return f"not installed ({exc.__class__.__name__})"


def cuda_report() -> tuple[bool, list[str]]:
    try:
        import torch

        available = bool(torch.cuda.is_available())
        names = [
            torch.cuda.get_device_name(index)
            for index in range(torch.cuda.device_count())
        ] if available else []
        return available, names
    except Exception:
        return False, []


def build_report() -> dict[str, Any]:
    cuda_available, gpu_names = cuda_report()
    return {
        "python_version": platform.python_version(),
        "python_full": sys.version,
        "platform": platform.platform(),
        "cuda_available": cuda_available,
        "gpu_names": gpu_names,
        "packages": {
            display_name: package_version(import_name)
            for display_name, import_name in PACKAGES.items()
        },
        "paper_runtime_reference": {
            "platform": "Kaggle Notebook",
            "gpu": "T4x2 GPU",
            "python": "3.12.3",
        },
        "note": (
            "Package versions describe the machine that generated this report. "
            "Regenerate on Kaggle before a reproduction run."
        ),
    }


def write_markdown(path: Path, report: dict[str, Any]) -> None:
    rows = [
        "# Environment",
        "",
        "> Auto-generated by `python scripts/99_env_report.py`.",
        "",
        "## Paper Runtime Reference",
        "",
        "- Platform: Kaggle Notebook",
        "- GPU: Kaggle T4x2 GPU",
        "- Python: 3.12.3",
        "- CUDA-enabled PyTorch environment",
        "",
        "## Report Generator Environment",
        "",
        f"- Python: {report['python_version']}",
        f"- Platform: {report['platform']}",
        f"- CUDA available: {report['cuda_available']}",
        f"- GPUs: {', '.join(report['gpu_names']) if report['gpu_names'] else 'none detected'}",
        "",
        "| Package | Version |",
        "|---|---|",
    ]
    rows.extend(
        f"| `{name}` | {version} |"
        for name, version in report["packages"].items()
    )
    rows.extend(
        [
            "",
            "Versions marked `not installed` are not guessed. Regenerate this file in the "
            "actual Kaggle T4x2 runtime used for reproduction.",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(rows), encoding="utf-8")


def main() -> None:
    report = build_report()
    json_path = Path("artifacts/logs_sample/environment_report.json")
    markdown_path = Path("docs/ENVIRONMENT.md")
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps(report, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    write_markdown(markdown_path, report)
    print(json.dumps(report, indent=2, ensure_ascii=False))
    print(f"Wrote {json_path} and {markdown_path}")


if __name__ == "__main__":
    main()
